# ./.tmuxinator.yml

name: chat_test
root: .

on_project_start: export RUST_BACKTRACE=1 && cargo build

startup_pane: 2

windows:
  - test:
      layout: even-horizontal
      panes:
        - export RUST_LOG=debug && cargo run -p server --bin main -- --address=127.0.0.1 --port 6969
        - cargo run -p client-tui -- --address=127.0.0.1 --port 6969
        - cargo run -p client-tui -- --address=127.0.0.1 --port 6969
