[package]
name = "client-tui"
version = "0.1.0"
edition = "2024"
description.workspace = true
authors.workspace = true

[[bin]]
name = "client-tui"
path = "src/bin/main.rs"


[dependencies]

# Chat server
server = { path = "../server" }

# Async
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }

# CLI Arguments
clap = { workspace = true }

# TUI
ratatui = "0.30.1"

# Logging
log = { workspace = true }
log4rs = "1.4"

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Time
chrono = { workspace = true }

# Serialization
serde = { workspace = true }
ciborium = { workspace = true }
